[build]
  base    = "docs/website"
  command = "[ -d themes/hugo-theme-relearn ] || git clone --depth 1 https://github.com/McShelby/hugo-theme-relearn.git themes/hugo-theme-relearn && hugo --minify --baseURL \"$URL\""
  publish = "public"

[build.environment]
  HUGO_VERSION = "latest"

# Deploy Previews (Pull Requests)
[context.deploy-preview]
  command = "[ -d themes/hugo-theme-relearn ] || git clone --depth 1 https://github.com/McShelby/hugo-theme-relearn.git themes/hugo-theme-relearn && hugo --minify --baseURL \"$DEPLOY_PRIME_URL\""

# Branch Deploys
[context.branch-deploy]
  command = "[ -d themes/hugo-theme-relearn ] || git clone --depth 1 https://github.com/McShelby/hugo-theme-relearn.git themes/hugo-theme-relearn && hugo --minify --baseURL \"$DEPLOY_PRIME_URL\""
